### ISSUE TITLE
[BUG] incorrect scan chosen for peptide level FDR

### ISSUE THREAD

**Issue by bmx8177** [Noble-Lab/crema#10]
It looks like Crema chooses the incorrect scan when doing peptide level FDR. Specifically, for a small number of peptides, it choose a scan that is not the best scoring PSM. Command and output is attached.

Look at peptide M[15.99]TWMKDGRPLPQTDQVQTLGGGEVLR, KGAAPAPPR, and KPPQALAK.

Command:
results =  psms.assign_confidence(score_column="combined p-value", desc=False, eval_fdr=0.01, method="tdc")

[tide-search.txt](https://github.com/Noble-Lab/crema/files/6970652/tide-search.txt)

**Comment by wfondrie** [comment]
Can you post your results too?

**Comment by wfondrie** [comment]
Can you elaborate on the problem? I only see one scan corresponding to each of those peptides in `tide-search.txt`:
```Python
import crema
import pandas as pd

peps =  ["M[15.99]TWMKDGRPLPQTDQVQTLGGGEVLR", "KGAAPAPPR", "KPPQALAK"]
psms = crema.read_crux("data/tide-search.txt")
orig = pd.DataFrame(psms.data)
print(orig[orig["sequence"].isin(peps)])
```
<table border="1" class="dataframe">  <thead>    <tr style="text-align: right;">      <th></th>      <th>scan</th>      <th>spectrum precursor m/z</th>      <th>refactored xcorr</th>      <th>delta_cn</th>      <th>res-ev p-value</th>      <th>combined p-value</th>      <th>exact p-value</th>      <th>delta_lcn</th>      <th>target/decoy</th>      <th>sequence</th>    </tr>  </thead>  <tbody>    <tr>      <th>693</th>      <td>5249</td>      <td>426.7701</td>      <td>0.70</td>      <td>0.170552</td>      <td>0.000389</td>      <td>0.002493</td>      <td>0.027958</td>      <td>0</td>      <td>True</td>      <td>KPPQALAK</td>    </tr>    <tr>      <th>734</th>      <td>4899</td>      <td>432.7483</td>      <td>0.75</td>      <td>0.000000</td>      <td>0.000561</td>      <td>0.002140</td>      <td>0.014676</td>      <td>0</td>      <td>True</td>      <td>KGAAPAPPR</td>    </tr>    <tr>      <th>5332</th>      <td>9886</td>      <td>977.1439</td>      <td>0.05</td>      <td>0.176544</td>      <td>0.000824</td>      <td>0.013821</td>      <td>0.305671</td>      <td>0</td>      <td>True</td>      <td>M[15.99]TWMKDGRPLPQTDQVQTLGGGEVLR</td>    </tr>  </tbody></table>

**Comment by bmx8177** [comment]
For each of these three peptides, Crema chooses the target scan when the decoy scan has a better score. Filter by  the 'original target sequence' column not the 'sequence' column.

For example - scan 4654 with decoy peptide KPAQALPK has a combined p-value score of 0.0024337054 
While scan 5249 with target peptide KPPQALAK has a combined p-value score of 0.0024932919 .
Crema keeps scan 5249 even though it has a worse score.

[crema.decoy.peptides.txt](https://github.com/Noble-Lab/crema/files/6971196/crema.decoy.peptides.txt)
[crema.peptides.txt](https://github.com/Noble-Lab/crema/files/6971197/crema.peptides.txt)

**Comment by wfondrie** [comment]
What version are you using? Here's what I get:

```Python
import crema
import pandas as pd

psms = crema.read_crux("data/tide-search.txt", peptide_tdc=True)
results = psms.assign_confidence(
    score_column="combined p-value", 
    desc=False, 
    eval_fdr=0.01, 
    method="tdc",
)

targets = results.confidence_estimates["peptides"]
print(targets[targets.sequence == "KPPQALAK"])
#Empty DataFrame
#Columns: [scan, spectrum precursor m/z, sequence, combined p-value, crema q-value]

decoys = results.decoy_confidence_estimates["peptides"]
print(decoys[decoys.sequence == "KPAQALPK"])
#Index: []
#     scan  spectrum precursor m/z  sequence  combined p-value  crema q-value
#692  4654                426.7686  KPAQALPK          0.002434       0.170066
```
I did run into what should be an unrelated bug related to a recent pandas update though. I haven't yet pushed the fix.

**Comment by bmx8177** [comment]
I was using version 0.0.5.dev44+g646f020. Just upgraded to 0.0.5. Will rerun and report back.

**Comment by wfondrie** [comment]
I'd recommend installing it directly from the main branch on GitHub:
```
pip install git+https://github.com/Noble-Lab/crema.git
```

**Comment by bmx8177** [comment]
Well this is going to be a pain to figure out. I upgraded Crema using Github. I still have the same issue. What OS are you using and what Python/Pandas version do you have? I'm hoping this isn't a Mac/Linux issue but it may be that.

**Comment by wfondrie** [comment]
I'm using on Python 3.8.8 and Pandas 1.3.1. I wonder if it is a random seed issue, such that the winner is currently random for some reason. I'll try it with different seeds.

**Comment by bmx8177** [comment]
After a discussion with Will I discovered that the default peptide level FDR calculation that Crema uses is NOT the picked peptide FDR calculation. There is currently a hidden parameter in the read_crux function (peptide_tdc) that should be set to True when trying to calculate the picked peptide FDR calculation.

After setting that parameter to True I got the following error
> pandas.core.base.DataError: No numeric types to aggregate

It appears that the problem is in line 169 of crux.py and that you can not do a groupby on non-numberic values.
>targets["ord"] = targets.groupby([seq, "mods"])["sequence"].rank("first")

**Comment by bmx8177** [comment]
And update. Ignore my last post (sorry!). It works if I use pandas version 1.3.1 but fail if I use version 1.0.3. It is probably worth noting in the documentation that you need >=1.0.3 for Pandas.

**Comment by wfondrie** [comment]
Phew! Cool. I've updated the minimum version of Pandas that will work with crema, so it should automatically install a compatible version in the future.
