### ISSUE TITLE
[BUG] Missing peptide in peptide level FDR

### ISSUE THREAD

**Issue by bmx8177** [Noble-Lab/crema#12]
The peptide below is found in tide-search.txt and the corresponding crema.psms.txt but is missing in crema.peptides.txt. I used picked peptide FDR procedure.
> LIAEYGMPSTHAMAATAIAFTLLISTM[15.99]DR

[crema.decoy.peptides.txt](https://github.com/Noble-Lab/crema/files/6984533/crema.decoy.peptides.txt)
[crema.decoy.psms.txt](https://github.com/Noble-Lab/crema/files/6984535/crema.decoy.psms.txt)
[crema.peptides.txt](https://github.com/Noble-Lab/crema/files/6984536/crema.peptides.txt)
[crema.psms.txt](https://github.com/Noble-Lab/crema/files/6984537/crema.psms.txt)
[runCrema.py.txt](https://github.com/Noble-Lab/crema/files/6984539/runCrema.py.txt)

**Comment by bmx8177** [comment]
I figured it out (it was something wrong on my end). I blame Friday. Sorry!

**Comment by wfondrie** [comment]
Is there documentation we need to clear up?

**Comment by bmx8177** [comment]
Nope - Crema did the right thing. I just had a typo in my grep..... <- it is that sort of day.
